### ISSUE TITLE
Invariant Violation: requireNativeComponent: "CTKBannerView" was not found in the UIManager.

### ISSUE THREAD

**Issue by agungvr** [wowmaking/react-native-iron-source#66]
Hi, i'm getting error in release mode, my app crash on launch .Please help how to fix this?

```
Fatal Exception: com.facebook.react.common.JavascriptException: Invariant Violation: requireNativeComponent: "CTKBannerView" was not found in the UIManager.

This error is located at:
    in CTKBannerView
    in c
    in RCTView
    in RCTView
    in RCTScrollView
    in R
    in RCTView
    in w
    in u
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in x
    in RNSScreen
    in C
    in ForwardRef
    in S
    in V
    in RNSScreenContainer
    in c
    in RCTView
    in A
    in Unknown
    in S
    in Unknown
    in L
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in RCTView
    in RCTView
    in ForwardRef
    in RCTView
    in C
    in ForwardRef
    in PanGestureHandler
    in Unknown
    in RCTView
    in C
    in ForwardRef
    in RCTView
    in G
    in Unknown
    in RNSScreen
    in C
    in ForwardRef
    in S
    in Unknown
    in RNSScreenContainer
    in c
    in Unknown
    in E
    in y
    in A
    in RNCSafeAreaProvider
    in Unknown
    in A
    in Unknown
    in GestureHandlerRootView
    in Unknown
    in w
    in Unknown
    in G
    in Unknown
    in Unknown
    in ForwardRef
    in Unknown
    in ForwardRef
    in X
    in RCTView
    in c
    in Unknown
    in A
    in RCTView
    in RCTView
    in C, stack:
exports@9:286
exports@190:1633
get@178:875
Ha@92:71962
ja@92:71453
Oa@92:71306
Ia@92:68600
Ia@-1
<unknown>@92:24827
unstable_runWithPriority@183:3503
dn@92:24774
fn@92:24709
Pa@92:65261
gl@92:89769
render@92:91914
exports@351:549
run@343:1310
runApplication@343:2322
value@27:3544
<unknown>@27:840
value@27:2798
value@27:812
value@-1

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:224)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by fearmear** [comment]
`CTKBannerView` is a part of [react-native-fbads](https://github.com/callstack/react-native-fbads).
