### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationC...

### ISSUE THREAD

**Issue by mustvlad** [wowmaking/react-native-iron-source#83]
```
NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
    at com.ironsource.mediationsdk.IronSourceObject.init(IronSourceObject.java:257)
    at com.ironsource.mediationsdk.IronSource.init(IronSource.java:86)
    at com.ironsource.mediationsdk.IronSource.init(IronSource.java:75)
    at co.squaretwo.ironsource.RNIronSourceModule$1.run(RNIronSourceModule.java:40)
    at android.os.Handler.handleCallback(Handler.java:938)
...
(6 additional frame(s) were not displayed)
```

Hi guys, 

We're having this issue on Android and could not understand where is coming from.
This seem to be something at the moment of the initialization of the SDK. 

```
// Set Iron Source consent
IronSource.setConsent(consent);

// Init IronSource SDK
const ISUserId = this.props.loggedIn ? 
  this.props.session.user_id : 
  (devicePushToken ? devicePushToken.data : "random-user");

const ISAppKey = Platform.OS === "android" ? 
  "xxxxxxxx" : 
  "xxxxxxxx";

await IronSource.initializeIronSource(ISAppKey, ISUserId, {
  validateIntegration: true,
});
```

This is how we're doing the init. Also this issue happens only to some users but we couldn't replicate it ourselves.

Any ideas?

Cheers'

**Comment by tarasvakulka** [comment]
The same issue. @fearmear Could you please look on it ? I began to see this crash after upgrade com.ironsource.sdk:mediationsdk to version 7.1.7

**Comment by mustvlad** [comment]
After updating to `com.ironsource.sdk:mediationsdk:7.1.8` the error changed its form a bit and seem to appear less often. But it's still there and causing random crashes.

I also spoke with the **IronSource** team but they basically just said that they don't support RN officially so they can't do much about it.

The current form: 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
    at com.ironsource.mediationsdk.C.a
    at com.ironsource.mediationsdk.IronSource.init
    at com.ironsource.mediationsdk.IronSource.init
    at co.squaretwo.ironsource.RNIronSourceModule$1.run(RNIronSourceModule.java:40)
    at android.os.Handler.handleCallback(Handler.java:914)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:241)
    at android.app.ActivityThread.main(ActivityThread.java:7582)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**Comment by hinciler** [comment]
Did you find any solutions on this issue?

**Comment by tarasvakulka** [comment]
> Did you find any solutions on this issue?

Still no.

**Comment by Valew17** [comment]
Hello!
Has anyone found a solution to this problem?

**Comment by tarasvakulka** [comment]
@Valew17 Hi. Take a look to this fork https://github.com/tarasvakulka/react-native-iron-source

**Comment by Valew17** [comment]
> @Valew17 Hi. Take a look to this fork https://github.com/tarasvakulka/react-native-iron-source

Thank you!
Already installed, we hope there will be no more such errors.
